#include <Windows.h>

#define IO_GETMW_BASEADDR            CTL_CODE(FILE_DEVICE_UNKNOWN,0x21653,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_READ_REQUEST              CTL_CODE(FILE_DEVICE_UNKNOWN,0x21656,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_WRITE_REQUEST             CTL_CODE(FILE_DEVICE_UNKNOWN,0x21657,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_KILL_PROCESS              CTL_CODE(FILE_DEVICE_UNKNOWN,0x21666,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_HIDE_PROCESS              CTL_CODE(FILE_DEVICE_UNKNOWN,0x48256,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_SET_CRITICAL_STAT         CTL_CODE(FILE_DEVICE_UNKNOWN,0x78256,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_DELETE_CRITICAL_STAT      CTL_CODE(FILE_DEVICE_UNKNOWN,0x18256,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_SYS_SHUTDOWN              CTL_CODE(FILE_DEVICE_UNKNOWN,0x64646,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_SYS_REBOOT                CTL_CODE(FILE_DEVICE_UNKNOWN,0x64645,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_SYS_POWEROFF              CTL_CODE(FILE_DEVICE_UNKNOWN,0x64644,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_LOCKDOWN_PROCESS_CREATION               CTL_CODE(FILE_DEVICE_UNKNOWN,0x66666,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_UNLOCK_PROCESS_CREATION                 CTL_CODE(FILE_DEVICE_UNKNOWN,0x12345,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)


typedef struct _KERNEL_READ_REQUEST {
	ULONG ProcessID, Address, Size;
	PVOID pBuff;
} KERNEL_READ_REQUEST, * PKERNEL_READ_REQUEST;


typedef struct _KERNEL_WRITE_REQUEST {
	ULONG ProcessID, Address, Size;
	PVOID pBuff;
} KERNEL_WRITE_REQUEST, * PKERNEL_WRITE_REQUEST;


typedef struct _KERNEL_KILL_PROCESS_REQUEST {
	ULONG ProcId;
} KERNEL_KILL_PROCESS_REQUEST, * PKERNEL_KILL_PROCESS_REQUEST;

typedef struct _KERNEL_HIDE_PROCESS_REQUEST {
	ULONG ProcId;
} KERNEL_HIDE_PROCESS_REQUEST, * PKERNEL_HIDE_PROCESS_REQUEST;

typedef struct _KERNEL_SET_DELETE_CRITICAL_PROCESS_STAT_REQUEST {
	ULONG ProcId;
} KERNEL_SET_DELETE_CRITICAL_PROCESS_STAT_REQUEST, * PKERNEL_SET_DELETE_CRITICAL_PROCESS_STAT_REQUEST;


typedef enum _SHUTDOWN_ACTION {
	ShutdownNoReboot,
	ShutdownReboot,
	ShutdownPowerOff
} SHUTDOWN_ACTION, * PSHUTDOWN_ACTION;
