#include <ntddk.h>

#define IO_GETMW_BASEADDR   CTL_CODE(FILE_DEVICE_UNKNOWN,0x21653,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_READ_REQUEST     CTL_CODE(FILE_DEVICE_UNKNOWN,0x21656,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_WRITE_REQUEST    CTL_CODE(FILE_DEVICE_UNKNOWN,0x21657,METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

typedef struct _READ_REQUEST_DATA {
	ULONG ProcessID, Address, Size;
	PVOID pBuff;
} READ_REQUEST_DATA, * PREAD_REQUEST_DATA;


typedef struct _WRITE_REQUEST_DATA {
	ULONG ProcessID, Address, Size;
	PVOID pBuff;
} WRITE_REQUEST_DATA, * PWRITE_REQUEST_DATA;

NTSTATUS PsLookupProcessByProcessId(
	HANDLE    ProcessId,
	PEPROCESS* Process
);