#pragma once
#include <ntifs.h>
typedef unsigned short WORD;
typedef struct _SE_AUDIT_PROCESS_CREATION_INFO SE_AUDIT_PROCESS_CREATION_INFO, * PSE_AUDIT_PROCESS_CREATION_INFO;
typedef struct _MMSUPPORT MMSUPPORT, * PMMSUPPORT;
typedef struct _HARDWARE_PTE HARDWARE_PTE, * PHARDWARE_PTE;
typedef struct __EPROCESS_QUOTA_BLOCK _EPROCESS_QUOTA_BLOCK;
typedef struct __PAGEFAULT_HISTORY _PAGEFAULT_HISTORY;
typedef struct _MM_AVL_TABLE MM_AVL_TABLE, * PMM_AVL_TABLE;
typedef struct _MMADDRESS_NODE MMADDRESS_NODE, * PMMADDRESS_NODE;
typedef struct _EX_FAST_REF EX_FAST_REF, * PEX_FAST_REF;


typedef struct MM_AVL_TABLE;

typedef struct _KEXECUTE_OPTIONS KEXECUTE_OPTIONS, * PKEXECUTE_OPTIONS;


typedef struct _KGDTENTRY KGDTENTRY, * PKGDTENTRY;


typedef struct _KIDTENTRY KIDTENTRY, * PKIDTENTRY;


typedef struct _KPROCESS KPROCESS, * PKPROCESS;

typedef struct _EPROCESS EPROCESS, * PEPROCESS;
